server:
  port: 9091

spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:product-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

